include_guard(GLOBAL)

# Generated by cpkg sync in normal online workflows.
# This copy is kept in-tree because this sandbox has the required module
# sources locally but cannot register the copied directories as submodules.
# Keep it aligned with wtrproject.toml.

set(WTR_MANAGED_REPOSITORIES
    BasicComponents
    ChassisController
    MotorDrivers
    Sensors
    VelocityProfile
)

set(WTR_MANAGED_PACKAGE_DIRS
    Modules/BasicComponents/libs/control/mit_pd
    Modules/BasicComponents/libs/control/pid_motor
    Modules/BasicComponents/libs/math/LinearAlgebra
    Modules/BasicComponents/libs/math/EKF
    Modules/BasicComponents/libs/concurrency
    Modules/BasicComponents/libs/utils/deque
    Modules/BasicComponents/libs/utils/fixed_map
    Modules/BasicComponents/libs/utils/ring_buffer
    Modules/BasicComponents/libs/utils/crc
    Modules/BasicComponents/libs/traits
    Modules/BasicComponents/protocol/UartRxSync
    Modules/BasicComponents/services/watchdog
    Modules/BasicComponents/bsp/can_driver
    Modules/BasicComponents/utils
    Modules/MotorDrivers/core
    Modules/MotorDrivers/controllers
    Modules/MotorDrivers/motors/DM
    Modules/Sensors/gyro/HWT101CT
    Modules/VelocityProfile/Core
    Modules/VelocityProfile/SCurve
    Modules/ChassisController/Core
    Modules/ChassisController/Chassis/Mecanum4
    Modules/ChassisController/Controller/Master
    Modules/ChassisController/Controller/Slave
    Modules/ChassisController/Localization/EKF
    Modules/ChassisController/Localization/JustEncoder
)

foreach(_wtr_package_dir IN LISTS WTR_MANAGED_PACKAGE_DIRS)
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}/CMakeLists.txt")
        message(FATAL_ERROR "Missing managed package '${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}'. Run cpkg sync.")
    endif()

    add_subdirectory(
        "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}"
        "${CMAKE_BINARY_DIR}/cpkg/${_wtr_package_dir}"
    )
endforeach()

set(WTR_DIRECT_PACKAGE_TARGETS
    Chassis::ControllerMaster
    Chassis::ControllerSlave
    Chassis::Mecanum4
    ChassisLocalization::EKF
    ChassisLocalization::JustEncoder
    MotorDrivers::Controller
    MotorDrivers::DM
    SensorGyro::HWT101CT
    libs::CRC
    libs::RingBuffer
    protocol::UartRxSync
    services::Watchdog
    traits
    utils
)

set(WTR_RESOLVED_PACKAGE_TARGETS
    libs::MIT_PD
    libs::PIDMotor
    Math::LinearAlgebra
    Math::EKF
    libs::Concurrency
    libs::Deque
    libs::FixedMap
    libs::RingBuffer
    libs::CRC
    protocol::UartRxSync
    services::Watchdog
    bsp::CANDriver
    utils
    MotorDrivers::Core
    MotorDrivers::Controller
    MotorDrivers::DM
    SensorGyro::HWT101CT
    VelocityProfile::Core
    VelocityProfile::SCurve
    Chassis::Core
    Chassis::Mecanum4
    Chassis::ControllerMaster
    Chassis::ControllerSlave
    ChassisLocalization::EKF
    ChassisLocalization::JustEncoder
    traits
    FreeRTOS
    stm32cubemx
)

add_library(wtr_project_dependencies INTERFACE)
target_link_libraries(wtr_project_dependencies INTERFACE ${WTR_DIRECT_PACKAGE_TARGETS})

function(wtr_link_packages target)
    target_link_libraries(${target} ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()

function(wtr_link_packages_public target)
    target_link_libraries(${target} PUBLIC ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()
